language: generic 
sudo: required
Services:
  - docker

before_install:
  - docker build -t sophiedodson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sophiedodson/react-test npm test 

after_success:
  - docker build -t sophiedodson/multi-client ./client
  - docker build -t sophiedodson/multi-nginx ./nginx
  - docker build -t sophiedodson/multi-server ./server
  - docker build -t sophiedodson/multi-worker ./worker
	# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
	# Take images and push them to docker hub
  - docker push sophiedodson/multi-client
  - docker push sophiedodson/multi-nginx
  - docker push sophiedodson/multi-server
  - docker push sophiedodson/multi-worker